name: Kubernetes Compatibility Matrix
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s_version: [v1.19.12-k3s1, v1.20.8-k3s1, v1.21.2-k3s1, latest]
        otp: [24.x]
        elixir: [1.13.x]
    steps:
      - uses: debianmaster/actions-k3s@master
        id: k3s
        with:
          version: ${{ matrix.k8s_version }}
      - uses: actions/checkout@v1.0.0
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      
      - name: Retrieve Build Cache
        uses: actions/cache@v1
        id: build-folder-cache
        with:
          path: _build
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Retrieve Mix Dependencies Cache
        uses: actions/cache@v1
        id: mix-cache
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get
      - run: TEST_KUBECONFIG=$KUBECONFIG TEST_WAIT_TIMEOUT=120 mix test --only integration --max-failures 1
